name = "deno_deploy_template"
version = "1.0.0"
licences = ["MIT"]
description = "Template for deploying a Nakai app on Deno Deploy"
repository = { type = "github", user = "nakaibuild", repo = "deno_deploy_template" }

[dependencies]
gleam_stdlib = "~> 0.22"
nakai = "~> 0.1"

[dev-dependencies]
gleeunit = "~> 0.6"
